model_list:
  - model_name: Wrench-35B-A3B-Q4_K_M-GGUF.gguf
    litellm_params:
      model: openai/Wrench-35B-A3B-Q4_K_M-GGUF.gguf
      api_base: "http://localhost:8001/v1"
      api_key: "dummy"

litellm_settings:
  success_callbacks: ["helicone"]